# Generated by Django 5.2.4 on 2025-07-04 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FamilyMember', '0001_initial'),
        ('Plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterings', to='FamilyMember.familymember')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterings', to='Plant.plant')),
            ],
        ),
    ]
