# Generated by Django 5.2.4 on 2025-07-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('grow_level', models.PositiveIntegerField(default=0)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='Family.family')),
            ],
        ),
    ]
