# Generated by Django 5.2.4 on 2025-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plant', '0002_remove_plant_last_watered_plant_watering_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
