# Generated by Django 5.2.4 on 2025-07-04 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_date', models.DateField(default=django.utils.timezone.localdate)),
                ('content', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Family.family')),
            ],
            options={
                'unique_together': {('family', 'q_date')},
            },
        ),
    ]
