# Generated by Django 5.2.4 on 2025-07-07 10:59

from django.db import migrations

def seed_questionpool(apps, schema_editor):
    QuestionPool = apps.get_model('Question', 'QuestionPool')
    QuestionPool.objects.bulk_create([
        QuestionPool(content="오늘 하루는 어땠나요?"),
        QuestionPool(content="최근에 기분 좋았던 일은?"),
        QuestionPool(content="가족에게 고마웠던 순간은?"),
        QuestionPool(content="이번 주에 하고 싶은 일은?"),
        QuestionPool(content="나만의 힐링 방법은?"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(seed_questionpool),
    ]
