# Generated by Django 5.2.4 on 2025-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('seeds', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
